export type SkillGroup = {
  title: string;
  blurb: string;
  items: string[];
};

export const skillGroups: SkillGroup[] = [
  {
    title: "Frontend",
    blurb: "Where most of my time goes.",
    items: [
      "TypeScript",
      "JavaScript",
      "React 19",
      "Next.js 16",
      "Tailwind CSS v4",
      "shadcn/ui",
      "Ant Design",
      "Material UI",
      "Radix UI",
      "Motion",
      "TanStack Query",
      "Zustand",
      "React Hook Form",
      "Zod",
      "SASS",
      "Bootstrap",
    ],
  },
  {
    title: "Mobile",
    blurb: "Cross-platform apps, shipped to both stores.",
    items: [
      "React Native",
      "iOS",
      "Android",
      "App architecture",
      "API integration",
      "Performance tuning",
    ],
  },
  {
    title: "Backend",
    blurb: "APIs, auth and background work.",
    items: [
      "Node.js",
      "NestJS",
      "Express",
      "Hono",
      "tRPC",
      "Laravel",
      "Prisma",
      "REST",
      "GraphQL",
      "Auth.js",
      "Better Auth",
      "Inngest",
      "Socket.IO",
      "Pusher",
    ],
  },
  {
    title: "Data & infrastructure",
    blurb: "Databases and the platforms I deploy to.",
    items: [
      "PostgreSQL",
      "Neon",
      "MySQL",
      "MongoDB",
      "SQLite",
      "Firebase",
      "Convex",
      "Appwrite",
      "Vercel",
      "Railway",
      "Render",
      "AWS",
      "Stripe",
      "Resend",
      "Sentry",
    ],
  },
  {
    title: "Practices",
    blurb: "How the work stays maintainable.",
    items: [
      "Clean architecture",
      "SOLID",
      "MVC",
      "OOP",
      "System design",
      "Database design",
      "Performance optimisation",
      "Code review",
      "Technical mentoring",
    ],
  },
  {
    title: "Tools & languages",
    blurb: "The rest of the bench.",
    items: [
      "Git",
      "Postman",
      "Chrome DevTools",
      "Ollama",
      "Vercel AI SDK",
      "PHP",
      "Python",
      "Java",
      "C / C++",
      "Machine Learning",
    ],
  },
];

/** Flat list for the marquee on the home page. */
export const marqueeStack = [
  "TypeScript",
  "React 19",
  "Next.js 16",
  "React Native",
  "Tailwind CSS",
  "Node.js",
  "NestJS",
  "Prisma",
  "PostgreSQL",
  "tRPC",
  "Hono",
  "Laravel",
  "Motion",
  "TanStack Query",
  "Zod",
  "Stripe",
  "Vercel",
  "Inngest",
  "Socket.IO",
  "MongoDB",
];
